### ISSUE TITLE
Running macOS build under GithubActionsCI fails with "error MSB3644: The reference assemblies for framework .NETFramework,Version=v4.7.2 were not found"

### ISSUE THREAD

**Issue by knocte** [mono/monodevelop#9174]
Build script:
```
name: macOS
on: push

jobs:
    build:
        runs-on: macOS-latest
        steps:
        - uses: actions/checkout@v1
        - name: Install build deps
          run: brew install automake
        - name: Build
          run: |
              ./configure
              make
```

Expected result: should succeed building. (I assume GithubActionsCI has the 'stable' channel of mono installed.)

Current results:

```
Build FAILED.

"/Users/runner/runners/2.159.2/work/monodevelop/monodevelop/main/Main.sln" (default target) (1) ->
"/Users/runner/runners/2.159.2/work/monodevelop/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" (default target) (2) ->
"/Users/runner/runners/2.159.2/work/monodevelop/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj" (default target) (3) ->
(GetReferenceAssemblyPaths target) -> 
  /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1195,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/runner/runners/2.159.2/work/monodevelop/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.57
```
